### ISSUE TITLE
Cividiscount codes/descriptions should not be exposed in receipts

### ISSUE THREAD

**Issue by Upperholme** [civicrm/org.civicrm.module.cividiscount#166]
Whilst I can see various use cases where it would be valuable to not have a discount code or the description text for the code included in the receipt/confirmation message that is sent to the purchaser, I can see no compelling reason why the code or the description should be written into the receipt by default.

Therefore my suggestion/request is to disable this functionality. All that needs to appear on the receipt is the amount/percentage of the discount that has been applied, and to display the correct figures on the receipt (i.e. gross amount, discount amount, net amount).

In many cases with my clients I find that they want to use the code for admin-only purposes, to enable discounts for speakers, volunteers, etc. at events and suchlike. Exposing these codes on the receipt opens up the possibility for end users to distribute these codes enabling others to get discounts whilst not necessarily being eligible for them.

Similarly with the descriptive text, we find that the primary value of this text is to act as a descriptive label for administrators to use, to help them identify which code is to use for any given application. Consequently, having to consider the fact that the end user will see this text on a receipt significantly constrains the value of this description field.

Maybe consider having admin-facing and user-facing texts as separate options? Perhaps implement an option switch to enable/disable the appearance of the code/description on the receipt? But please default to having it disabled.

Thanks for considering this.

**Comment by Stoob** [comment]
I am going to tag on to this issue, because it is related issue dealing with "automatically applied" discounts, we do not want to show the code either.

1. Let's say for example, I create a code called "event20" wherein a current member gets an automatic 20% off event registration.
2. when a member registers for an event, the discount is automatically applied, that is all well and good
3. but what is NOT ok is that "event20" is shown in the green bar such that it says: "Includes applied discount code event20"
4. this code "event20" WILL work when anyone who is not a member tries to use it, and it is not good that this code is exposed and can thus be shared @Upperholme

**Comment by Stoob** [comment]
![show-d](https://user-images.githubusercontent.com/1683473/50742544-71602f00-11c1-11e9-8e87-3dd0faa83b40.png)

**Comment by Upperholme** [comment]
Excellent.

**Comment by colemanw** [comment]
@Upperholme - the PR has been merged, does that resolve this issue completely or is there more?
