### ISSUE TITLE
Stacking discounts

### ISSUE THREAD

**Issue by AlishaGNYC** [civicrm/org.civicrm.module.cividiscount#246]
It would great to be able to stack discounts in Civi. For example, we want to give all members 10% off. We also want to give certain members another 10% off. 

Is there any thought of adding that functionality to CiviDiscount?

**Comment by Stoob** [comment]
This would be a cool feature, but it should be _optional_ because not every organization wants to stack. For example, if a 20% discount and a $20 off discount apply to the same event, it could conceivable result in a $0 registration which may not be what is desired.  Some organizations specifically want NOT to stack and instead provide the single discount with the largest benefit.

**Comment by Stoob** [comment]
duplicate see https://github.com/civicrm/org.civicrm.module.cividiscount/issues/161

**Comment by mlutfy** [comment]
CiviDiscount has moved to CiviCRM's Gitlab! (see #273)

If you are interested in this issue, you can follow it here:  
https://lab.civicrm.org/extensions/cividiscount/-/issues/246
