### ISSUE TITLE
Price field options missing if there are two or more price sets that contain fields with the same label

### ISSUE THREAD

**Issue by freeform-sg** [civicrm/org.civicrm.module.cividiscount#265]
[Original discussion on StackOverflow](https://civicrm.stackexchange.com/questions/39819/discounts-price-sets-disappeared)

As of version 3.8.3 there appears to be an issue if any price fields from different price sets share any labels. Here are the steps to reproduce:

1. Create a price set of type event, add multiple fields
2. Duplicate the price set, without changing the labels of any of the fields
3. Create an event and select the 1st price set
4. Create a second event and select the 2nd price set
5. Create a discount code and view the available price fields: for each price set you created only 1 field's options will be available ([Screenshot 1](https://i.stack.imgur.com/KsVms.png))
6. Attempt to create a discount code again and this time all price fields from both price sets should be available ([Screenshot 2](https://i.stack.imgur.com/8dLPB.png))

Additionally; if you change the labels so that only 1 field label is not unique, then you will see:

- Price set 1 options: Only the field whose label is NOT unique
- Price set 2 options: Only the fields whose labels ARE unique
([Screenshot 3](https://i.stack.imgur.com/Wy9X0.png))

**Comment by freeform-sg** [comment]
The issue appears to remain if you downgrade from 3.8.3 or 3.8.4 back to 3.8.1 - but I didn't discover what the issue was until I'd already updated the site, so I am not sure if it also exists with 3.8.1, which would suggest it may have cropped-up after the release CiviCRM 5.38.0. Would need to test CiviDiscount 3.8.1 on a site running 5.38.0 to confirm if it was due to the CiviCRM update or the CiviDiscount update.

**Comment by freeform-sg** [comment]
I retested a fresh install of CiviDiscount 3.8.1 on CiviCRM 5.38.0 and the issue exists there as well. Our previous version was 5.37.2 but I am unsure when the problem began, whether it was before or after the update to 5.38.0.

**Comment by midnightspenguin** [comment]
I found that not only did they have to have unique names, but that it is only looking at a certain number of characters to see if it is unique. So when I added the dates to the end of each name, nothing changed. When I added them to the beginning of the name, then they were all available as fields for discounts.

**Comment by herbdool** [comment]
After looking into this a bit I believe there's an easy patch. At https://github.com/civicrm/org.civicrm.module.cividiscount/blob/3515fc559b102384bed7b9fb4382314882370aad/CRM/CiviDiscount/Utils.php#L85 if you also sort by Price Set ID it'll create the select optgroups properly. Make it:

```
ORDER BY  ps.id, pf_label, pfv.price_field_id, pfv.weight
```

Or it could be sorted by Price Set Title as well since they're required to be unique.

**Comment by herbdool** [comment]
PR: https://github.com/civicrm/org.civicrm.module.cividiscount/pull/270

**Comment by Upperholme** [comment]
I would really welcome prompt new release where this is resolved. I'm in the midst of organising a significant event with lots of discount codes involved, and can't currently get any of those codes set up due to this issue. Already lost half a day trying to re-label fields and price options, but can't currently get the workaround to take effect. Tearing hair out...

**Comment by herbdool** [comment]
@Upperholme if you test this https://github.com/civicrm/org.civicrm.module.cividiscount/pull/270 by patching your site and provide feedback here, that might help the fix getting accepted.

**Comment by Upperholme** [comment]
Working on it...

**Comment by Upperholme** [comment]
OK. just implemented #270 and all my price fields and options are available to me when setting up discount codes. My one comment, and it's purely a UX issue, is that the price fields now appear to be listed with the most recent price sets at the bottom of the list, where it might be nicer/more relevant if they were at the top. But otherwise this looks good. Using D7, Civi 5.39, and the current release of the Cividiscount extension. Many thanks @herbdool

**Comment by herbdool** [comment]
@Upperholme great!

Right now it's sorting by the price set ID ascending. It could either be sorted by price set descending, or be sorted alphabetically by the price set labels (which are unique). Which would be best?

**Comment by Upperholme** [comment]
For me I think price set descending probably makes most sense.

**Comment by herbdool** [comment]
@Upperholme I've made it descending now. I don't have an opinion either way.

**Comment by Upperholme** [comment]
Thanks. I'll update and feed back.

**Comment by herbdool** [comment]
@mattwire we've got a simple PR which has been tested and confirmed that it fixes the issue. Thanks!

**Comment by Upperholme** [comment]
Yes - descending makes more sense, at least in my use case, where I have lots of price sets in play. It puts the most recent sets at the top of the list, and so quicker to access. Thanks again.
