### ISSUE TITLE
CiviDiscount, Discounts for events, the option "Any event" does not work

### ISSUE THREAD

**Issue by agileware-justin** [civicrm/org.civicrm.module.cividiscount#272]
Using CiviCRM 5.40.1, CiviDiscount 3.8.4 and WordPress 5.8.

**Steps to reproduce**

1. Create a Discount Code
2. Set a discount amount
3. In the section "Discounts for events", select Events: "-- any event ---"
4. Go to an Event Registration form, try locate the Discount Code field on the form.
5. The Discount Code field is not shown on the form.

Discounts for events with the option "-- any event ---" does not work.

**Workaround**
The workaround is to select all the available Event Types, then the discount is available for all events and it can be applied.

Agileware Ref: CIVICRM-1774

**Comment by lkuttner** [comment]
Please describe the behavior that you are seeing when you try to use it.  "does not work" is not sufficiently descriptive .

**Comment by agileware-justin** [comment]
Have moved this comment to the main issue description.

**Comment by lkuttner** [comment]
This appears to be related to the issues that I am seeing on our dev server after updating to 3.8.4. I am not seeing events in the event list for new Price Sets or ones that have been created since changes were made to Price Sets around two years ago.  It appears that changes have been made to possibly both Price Sets and CiviDiscount that are not cross-compatible.
See my comments [https://lab.civicrm.org/dev/core/-/issues/2727#note_62628](https://lab.civicrm.org/dev/core/-/issues/2727#note_62628) and [https://lab.civicrm.org/dev/core/-/issues/2727#note_62692](https://lab.civicrm.org/dev/core/-/issues/2727#note_62692) in this other issue with automatic discounts not being applied.

**Comment by gibsonoliver** [comment]
Also seeing exactly the same issue. Checked on 2 different sites

> Using CiviCRM 5.40.1, CiviDiscount 3.8.4 and WordPress 5.8.
> 
> **Steps to reproduce**
> 
> 1. Create a Discount Code
> 2. Set a discount amount
> 3. In the section "Discounts for events", select Events: "-- any event ---"
> 4. Go to an Event Registration form, try locate the Discount Code field on the form.
> 5. The Discount Code field is not shown on the form.
> 
> Discounts for events with the option "-- any event ---" does not work.
> 
> **Workaround**
> The workaround is to select all the available Event Types, then the discount is available for all events and it can be applied.
> 
> Agileware Ref: CIVICRM-1774

**Comment by agileware-justin** [comment]
I don't think this extension is _currently being maintained_ @gibsonoliver - see https://github.com/civicrm/org.civicrm.module.cividiscount/issues/273 - looking for new maintainers

**Comment by mlutfy** [comment]
CiviDiscount has moved to CiviCRM's Gitlab! (see #273)

If you are interested in this issue, you can follow it here:  
https://lab.civicrm.org/extensions/cividiscount/-/issues/272
