### ISSUE TITLE
Rename extension to org.civicrm.cividiscount because it is not a Drupal module

### ISSUE THREAD

**Issue by agileware-justin** [civicrm/org.civicrm.module.cividiscount#274]
Rename extension to org.civicrm.cividiscount because it is not a Drupal module

**Comment by colemanw** [comment]
IMO renaming an extension should only be done if absolutely necessary because it can cause so many problems.
Recently I had to rename `org.civicrm.search` -> `org.civicrm.search_kit` because the short name "search" conflicted with a Drupal module of the same name and messed up Drupal's hook dispatcher. So we renamed it and added an upgrade routine to civi to fix the old name. But in that case we had the luxury of the extension being distributed with core so we could add that upgrader. And even then we got some bug reports of weird stuff caused by the change. With a non-core extension like this one, and with thousands of users, I think a name change would wreak havoc :thinking:

**Comment by mattwire** [comment]
Agree with @colemanw - currently it is not a simple thing to do and causes various problems. It would be nice if this was better supported by civicrm core but perhaps an "easier" route is to continue the work to hide the extension "key" in the UI - for example I recently changed the extensions UI so it displayed the description instead of the key.

**Comment by mlutfy** [comment]
We can move this repo to Gitlab and just call it "cividiscount" (and agree that the ext-key has become mostly irrelevant).

edit: seems that Gitlab is being discussed here: https://github.com/civicrm/org.civicrm.module.cividiscount/issues/273#issuecomment-896856942

**Comment by mattwire** [comment]
@mlutfy @agileware-justin See https://github.com/civicrm/civicrm-core/pull/21094 for a bit more work towards hiding extension key in UI.

**Comment by agileware-justin** [comment]
Renaming an extension shouldn't cause the system to crash or be left in an unusable state. That's the issue.

**Comment by colemanw** [comment]
Sometimes "shouldn't" has conflicts with the real world. But Civi isn't the only one with this problem. Try suggesting to a Drupal module or WP plugin maintainer that they change the machine name of *their* project and see what kind of reception you get :)

But really it's not just modules and extensions. Changing the machine name of activity types, case types, relationships, events, just about *anything* in a database is going to wreak havoc because machine names are supposed to be stable and unchanging. So when they do change it causes, well, instability.

**Comment by mlutfy** [comment]
migrated: https://lab.civicrm.org/extensions/cividiscount/-/issues/274
