### ISSUE TITLE
Multiple Criteria Matching For Discounts

### ISSUE THREAD

**Issue by galileo81580** [civicrm/org.civicrm.module.cividiscount#38]
I have a discount scenario where a "customer" is only eligible for the discount if they're purchasing two memberships (different programs in our organization).  It's a $25/each or $35 for two situation.

It doesn't look like there's any facility for checking discount eligibility based on "and" criteria instead of "or" criteria.  I'd be interested in working on that, but I've never written for Civi before.  Any estimation of how complex that would be?

**Comment by zorgalina** [comment]
Looks like no one  answered you for nearly a year - if you still are interested, I would say that it may take you a couple of weeks, if you have experience coding w/jQuery, php and MySQL and debugging.  If you've worked on Drupal/Joomla/WP it should not be so different, and since the discounting is an extension rather than core code it should not be so hard to not break other things.
