### ISSUE TITLE
discount for additional participants

### ISSUE THREAD

**Issue by Upperholme** [civicrm/org.civicrm.module.cividiscount#88]
In the readme it states "Option to apply discounts to additional participants". I'm not clear what this mean, or indeed how to activate if useful.

It might simpy mean that any given discount code can be optionally applied to all participants being registered, where the form allows the user to register multiple participants. If so, that's fine, but I can't see how to turn this option on or off.

My use case is different. I'd like to set a price person, and then enable a discount for each additional person registered at the same time. That would go something like 50 for the first person and 40 for each additional person.

Alternatively I could use a discount that gave a percentage driven by the total number of participants registered at the same time. something like 5% off if you book three people onto the event, or10% off if you book five people or more on.

So, this might simply be a support request, seeking clarification of what the statement "Option to apply discounts to additional participants" means, or it might be perceived as as a feature request.

**Comment by sturad** [comment]
I'm also interested in an option to have a price discounted if a certain amount of people registered. Ideally this would be not by applying a code, but simply by the participant count on the registration form.

**Comment by thoni56** [comment]
+1

**Comment by martinh-pw** [comment]
I am much too late for this ticket, but I've been having the same issue (not the discount model, but trying to find where the "additional participants" setting is).

So for anyone coming after us, this functionality appears to be implemented but the UI setting doesn't exist yet. To toggle the behavior find the function _cividiscount_allow_multiple() in cividiscount.php and change the return value. For 3.7 this is on line 941 of that file.

Yes I know you're not supposed to modify the code for an extension in-place, but that will accomplish what you want. :)  Otherwise, if someone is feeling ambitious you can try implementing a settings page!

**Comment by mlutfy** [comment]
CiviDiscount has moved to CiviCRM's Gitlab! (see #273)

If you are interested in this issue, you can follow it here:  
https://lab.civicrm.org/extensions/cividiscount/-/issues/88
